export const ACTIONS = {
    UPDATE_ROSE_A: 'UPDATE_ROSE_A',
    UPDATE_ROSE_B: 'UPDATE_ROSE_B',
    UPDATE_INTERPOLATION: 'UPDATE_INTERPOLATION',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    SET_PLAYING: 'SET_PLAYING',
    SET_RECORDING: 'SET_RECORDING',
    SYNC_PARAM: 'SYNC_PARAM',
    // ...
};
