export const ACTIONS = {
    UPDATE_ROSETTE_A: 'UPDATE_ROSETTE_A',
    UPDATE_ROSETTE_B: 'UPDATE_ROSETTE_B',
    UPDATE_HYBRID: 'UPDATE_HYBRID',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    SET_PLAYING: 'SET_PLAYING',
    SET_RECORDING: 'SET_RECORDING',
    SYNC_PARAM: 'SYNC_PARAM',
    // ...
};
